adding new conditioning for td modes
dingo-gw/dingo pull request #217
Opened 2023-09-19 19:44 UTC by hectorestelles

This PR adds a conditioning method for TD modes mimicking the standard behaviour of conditioning routines in LAL and GWSignal, i.e, starting the modes at a lower frequency for tapering not-in-band cycles and adding some extra buffer times.

2023-09-20 11:13 UTC, stephengreen requested changes
Looks good, just a few minor comments on naming conventions and adding docstrings. Please run Black on all the files you changed.

I will commit an improvement to the test as well.

2023-09-20 11:13 UTC, stephengreen commented on dingo/gw/waveform_generator/waveform_generator.py
> +        f_min, new_fstart, textra, original_f_min, fisco = wfg_utils.get_starting_frequency_for_conditioning(parameters_gwsignal)
Keep to a standard variable name convention, e.g., `new_f_start`, `t_extra`, `f_isco`.

2023-09-20 11:13 UTC, stephengreen commented on dingo/gw/waveform_generator/wfg_utils.py
> +    h_tapered = lal.CreateREAL8TimeSeries(
Call this `h_tapered_re` for consistency with `h_tapered_im`.

2023-09-20 12:34 UTC, stephengreen commented
I improved the mode reconstruction tests, including now a test for SEOBNRv5HM. When I ran the test on SEOBNRv5HM 1,000 times, I found mismatches up to 0.1. For SEOBNRv5PHM they stayed below 1e-7. Generally, mismatches are worse for HM than PHM.

2023-09-20 13:57 UTC, stephengreen commented
Also, since we now have a unit test for v5 waveforms, do we need to adjust the dependencies of Dingo, e.g., minimum version numbers to have v5 included?

2023-09-25 11:27 UTC, hectorestelles commented
Hi @stephengreen I tried to address the comments on commit https://github.com/dingo-gw/dingo/pull/217/commits/18c9b30ff77dd9da0bf170d95230dedc907893f2 

Let me know if you have further suggestions

2023-09-26 10:04 UTC, stephengreen reviewed
Looks good. I updated the test tolerances and added a comment on the unit conversions.

Do we need to specify a minimum lalsimulation version for this test to pass?

2023-09-26 11:26 UTC, hectorestelles commented
> Looks good. I updated the test tolerances and added a comment on the unit conversions.
> 
> Do we need to specify a minimum lalsimulation version for this test to pass?

Yes, we would need to request lalsimulation>=7.15, in order to have gwsignal on it.

2023-09-26 13:38 UTC, stephengreen approved these changes

2023-09-26 13:39 UTC, merged